### ISSUE TITLE
Import Error 

### ISSUE THREAD

**Issue by Alan-Penkar** [jpfeltracco/rc-ssl-logtools#1]
I have boost, protobuf, and all the other dependencies, but I'm getting an import error when I try and decode the log files from the given link.  Tried it with system python and a virtualenv on Ubuntu 17.10, Python 3.6.3.  

`
Traceback (most recent call last):
  File "/home/alan/.pyenv/versions/DS/bin/ssldump", line 6, in <module>
    import rc_ssl_logtools
  File "/home/alan/Documents/DS/LogData/rc-ssl-logtools/rc_ssl_logtools/__init__.py", line 1, in <module>
    from .ssl_importer import log_frames
  File "/home/alan/Documents/DS/LogData/rc-ssl-logtools/rc_ssl_logtools/ssl_importer.py", line 16, in <module>
    from rc_ssl_logtools.proto import messages_robocup_ssl_wrapper_pb2
ImportError: cannot import name 'messages_robocup_ssl_wrapper_pb2'
`

**Comment by jpfeltracco** [comment]
@Alan-Penkar Could you try installing version 0.0.4 that just got uploaded to the python package index? I removed some of the auto protobuf generation stuff that was potentially causing trouble.

**Comment by Alan-Penkar** [comment]
Worked perfectly- thanks a lot.
